name: CD

on:
  push:
    branches: [ zi ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for modified files
      id: check_files
      run: |
        echo "::set-output name=changed::$(git diff --name-only HEAD^ HEAD)"

    - name: Skip if no relevant file changes
      if: ${{ steps.check_files.outputs.changed == '' }}
      run: |
        echo "No relevant file changes. Skipping workflow."
        exit 0

    - name: Run script
      run: |
        chmod +x ./makedeb.sh
        ./makedeb.sh

    - name: Create tag
      id: create_tag
      run: |
        TAG_NAME=$(date +v%Y%m%d%H%M%S)
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag $TAG_NAME
        echo ::set-output name=tag::${TAG_NAME}

    - name: Push tag
      run: git push origin --tags

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        release_name: Release ${{ steps.create_tag.outputs.tag }}
        draft: false
        prerelease: false
        body: |
          This release was automatically published by GitHub Actions.

    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./yadyn.deb
        asset_name: yadyn.deb
        asset_content_type: application/octet-stream
